name: UI Tests with WinAppDriver

on:
  pull_request:
    branches: [ main ]

jobs:
  winappdriver-tests:
    runs-on: [self-hosted, windows]

    steps:
    - name: Check if .NET is already installed
      shell: powershell
      run: |
        $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
        if ($null -eq $dotnet) {
          Write-Host ".NET not found. Installing..."
        } else {
          Write-Host ".NET is already installed. Version: $(dotnet --version)"
        }

    - name: Setup .NET
      if: steps.check_dotnet.outcome == 'failure'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.203'

    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Start WinAppDriver
      run: Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
