name: UI Tests with WinAppDriver

on:
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: [self-hosted, windows]

    steps:
    - name: Check if .NET is already installed
      shell: powershell
      run: |
        $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
        if ($null -eq $dotnet) {
          Write-Host ".NET not found. Installing..."
        } else {
          Write-Host ".NET is already installed. Version: $(dotnet --version)"
        }

    - name: Setup .NET ${{ env:DOTNET_VERSION }}
      if: steps.check_dotnet.outcome == 'failure'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env:DOTNET_VERSION }}

    - name: Checkout PR branch
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env:BUILD_CONFIGURATION }}

    - name: Start WinAppDriver
      run: Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

    - name: Test
      run: |
        if ($env:ENABLE_CODE_COVERAGE -eq "true") {
          dotnet test --no-build --configuration ${{ env:BUILD_CONFIGURATION }} --collect:"XPlat Code Coverage"
        } else {
          dotnet test --no-build --configuration ${{ env:BUILD_CONFIGURATION }}
        }
